### ISSUE TITLE
 THREAD WARNING: Plugin should use a background thread.

### ISSUE THREAD

**Issue by lunardog** [PatrickHeneise/cordova-ios-statusbar#8]
I'm getting warnings when running my app:

```
THREAD WARNING: ['StatusBar'] took '50.058838' ms. Plugin should use a background thread.
```

Following [this guide](http://docs.phonegap.com/en/edge/guide_platforms_ios_plugin.md.html), it seems that this pattern removes the warning without breaking the functionality:

```
- (void)whiteTint:(CDVInvokedUrlCommand*)command {
[self.commandDelegate runInBackground:^{
    CDVPluginResult* pluginResult = nil;

    self.callbackId = command.callbackId;

    dispatch_async(dispatch_get_main_queue(), ^{
        [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:YES];
        [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];
    });

    pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}];
}
```

It feels snappier as well, although that might be an illusion.

**Comment by thisarasr** [comment]
what is command delegate here?

**Comment by wilsolutions** [comment]
Hi, please, any update on this?

**Comment by PatrickHeneise** [comment]
There's an official plugin by PhoneGap by now: https://github.com/phonegap-build/StatusBarPlugin

**Comment by nottinhill** [comment]
@lunardog How did you implement the code in CDVStatusBar.h and CDVStatusBar.m ? Are there any plans to implement this into production code by Cordova Statusbar Plugin Team?

**Comment by lunardog** [comment]
@nottinhill, sorry about dropping the thread, I got switched to another project, platform, programming language and all.

Does the official plugin suggested by @PatrickHeneise solve the issue? If not, maybe it's a good idea to post it there? https://github.com/phonegap-build/StatusBarPlugin

**Comment by nottinhill** [comment]
What do you mean by official? I use Cordova with Ionic.
